shim-version: v0.1.8@sha256:795145f871b66946ab7755eb71fce866a92e4035a95d6f949ad79adee7294648
cvm-version: 0.1.3
ovmf-version: 0.0.2
cpus: 8
memory: 32768

models:
  - name: "deepseek-r1-70b"
    repo: "casperhansen/deepseek-r1-distill-llama-70b-awq@a1ab7653aae77fbabc536cbcbac5bb2e2fb5354f"
    mpk: "8e39a53227ccb0c3cffbed1c0013d4d63c74c1e01541b953ff021e91cb158330_39785418752_efe58861-8b9c-5e64-b0ee-85d9169acb44"
vllm-args: --quantization awq_marlin --max-model-len 65536

shim:
  listen-port: 443
  upstream-port: 8080
  control-plane: https://api.tinfoil.sh
  publish-attestation: true
  tls-challenge: dns
  paths:
    - /v1/chat/completions
    - /metrics
  origins:
    - https://tinfoil.sh
    - https://chat.tinfoil.sh
    - http://localhost:3000
